SELECT table_name FROM dba_tables WHERE owner = 'HAL';
/
SELECT default_tablespace FROM dba_users WHERE username = 'HAL';
/
SELECT file_name FROM dba_data_files 
WHERE tablespace_name = (SELECT default_tablespace FROM dba_users WHERE username = 'HAL');
/
CREATE TABLESPACE HAL_DATA
DATAFILE '/mnt/database_data/oradata/HAL/hal_data01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;
/
ALTER USER HAL DEFAULT TABLESPACE HAL_DATA;
/
ALTER USER HAL QUOTA UNLIMITED ON HAL_DATA;
/
ALTER TABLE HAL.ARTICLE_COLLECTIONS MOVE TABLESPACE HAL_DATA ONLINE;
ALTER TABLE HAL.RESEARCH_ARTICLES MOVE TABLESPACE HAL_DATA ONLINE;
ALTER TABLE HAL.ARTICLE_ABSTRACTS MOVE TABLESPACE HAL_DATA ONLINE;
ALTER TABLE HAL.ARTICLE_AUTHORS MOVE TABLESPACE HAL_DATA ONLINE;
ALTER TABLE HAL.ARTICLE_KEYWORDS MOVE TABLESPACE HAL_DATA ONLINE;
ALTER TABLE HAL.ARTICLE_DOMAINS_CODE MOVE TABLESPACE HAL_DATA ONLINE;
ALTER TABLE HAL.ARTICLE_DOMAINS_EN MOVE TABLESPACE HAL_DATA ONLINE;
ALTER TABLE HAL.ARTICLE_DOMAINS_FR MOVE TABLESPACE HAL_DATA ONLINE;
/
SELECT index_name 
FROM dba_indexes 
WHERE owner = 'HAL' AND status = 'UNUSABLE';
/
SELECT segment_name, segment_type, tablespace_name 
FROM dba_segments 
WHERE owner = 'HAL';
/
SELECT table_name, column_name, segment_name, tablespace_name
FROM dba_lobs
WHERE owner = 'HAL' 
  AND tablespace_name = 'HAL_DATA';
/
ALTER TABLE HAL.ARTICLE_ABSTRACTS MOVE LOB (ABSTRACT_TEXT) STORE AS (TABLESPACE HAL_DATA);
ALTER TABLE HAL.RESEARCH_ARTICLES MOVE LOB (LABEL) STORE AS (TABLESPACE HAL_DATA);
ALTER TABLE HAL.RESEARCH_ARTICLES MOVE LOB (TITLE) STORE AS (TABLESPACE HAL_DATA);
/
SELECT 
    tablespace_name, 
    used_space * 8192 / 1024 / 1024 / 1024 AS used_gb,
    tablespace_size * 8192 / 1024 / 1024 / 1024 AS total_gb,
    used_percent
FROM dba_tablespace_usage_metrics
WHERE tablespace_name IN ('USERS', 'HAL_DATA');
/
SELECT 
    segment_type, 
    SUM(bytes)/1024/1024 AS size_mb 
FROM dba_segments 
WHERE owner = 'HAL' 
GROUP BY segment_type;